language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pandas
  - pip install matplotlib
  - pip install git+https://github.com/UBC-MDS/ssg_pymeans.git
  - pip install pytest
# command to run tests
script: pytest
